name: whatthebook
description: "A book reading and writing platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  printing: ^5.11.1
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3

  # Database & Storage
  supabase_flutter: ^2.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  firebase_core: ^3.14.0
  
  # Utils
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.0
  image_picker: ^1.1.2
  image: ^4.1.3
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  flutter_markdown: ^0.7.7+1
  shared_preferences: ^2.2.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  flutter_pdfview: ^1.3.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.10.2
  
  url_launcher: ^6.2.5
  
  # Logging
  logger: ^2.0.2+1
  web: ^1.1.0

  # Rich Text Editor
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0

  # Time formatting
  timeago: ^3.6.1

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^30.1.38
  fl_chart: ^1.0.0
  google_sign_in: ^7.1.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - asset/images/
    - asset/privacy_policy.md
    - asset/terms_of_service.md
