// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaYaQJtUL0RvrNVIaPrNB2iQrdjJirmQ',
    appId: '1:327096289049:web:01c6c67bd95276be5f2788',
    messagingSenderId: '327096289049',
    projectId: 'whatbook-c7210',
    authDomain: 'whatbook-c7210.firebaseapp.com',
    databaseURL: 'https://whatbook-c7210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatbook-c7210.firebasestorage.app',
    measurementId: 'G-C4GX6CRLDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxpeMO86a9L48sm6k5un4n6YkAJ7zcmrk',
    appId: '1:327096289049:android:7ed4a0e3307d96565f2788',
    messagingSenderId: '327096289049',
    projectId: 'whatbook-c7210',
    databaseURL: 'https://whatbook-c7210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatbook-c7210.firebasestorage.app',
  );

}